export const PRODUCT_SPECIFICATIONS = ['99.98%', '99.95%', '99.90%', '99%'] as const;
export type ProductSpecification = (typeof PRODUCT_SPECIFICATIONS)[number];

export const FOB_DEDUCTION_SETTING_KEY = 'FOB_DEDUCTION_AMOUNT';
export const DEFAULT_FOB_DEDUCTION = 70;

export const EXCHANGE_RATE_SOURCES = {
  API: 'API',
  MANUAL: 'MANUAL',
} as const;

/** Align with ContainerStatus in enums.ts (PDF §10.4). */
export const CONTAINER_STATUSES = {
  DRAFT: 'DRAFT',
  UNDER_PREPARATION: 'UNDER_PREPARATION',
  PRODUCTION_ASSIGNED: 'PRODUCTION_ASSIGNED',
  UNDER_PROCESSING: 'UNDER_PROCESSING',
  PROCESSING_COMPLETED: 'PROCESSING_COMPLETED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED_FROM_FACTORY: 'DISPATCHED_FROM_FACTORY',
  REACHED_PORT: 'REACHED_PORT',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED',
  PLANNED: 'PLANNED',
} as const;

export const AMENDMENT_ELIGIBLE_STATUSES = [
  'REACHED_PORT',
  'READY_FOR_DISPATCH',
  'PARTIALLY_DISPATCHED',
  'FULLY_DISPATCHED',
] as const;
